server:
  port: 8082

spring:
  application:
    name: upload-service
  servlet:
    multiple:
      max-file-size: 5MB #????????
  datasource:
    url: jdbc:mysql://localhost:3306/heima
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10089/eureka
    instance:
      lease-renewal-interval-in-seconds: 5 # ??5???????
      lease-expiration-duration-in-seconds: 10 # 10???????
      prefer-ip-address: true
      ip-address: 127.0.0.1
      instance-id: ${spring.application.name}:${server.port}

fdfs:
  so-timeout: 2000
  connect-timeout: 601
  thumb-image: # ???
    width: 60
    height: 60
  tracker-list: # tracker??
    - 123.57.186.129:22122