server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/heima
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10

logging:
  level:
    com.leyou.item.mapper.*: debug

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10089/eureka
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true # 当你获取host时，返回的不是主机名，而是ip
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

info:
  app.name: zy


